=== iashtripathy/WebProgrammingPart1/xml/order.dtd
<!ELEMENT order (customername,age,gender,Item+)>
<!ATTLIST order id CDATA #IMPLIED>
<!ELEMENT Item (ItemId,ItemName,price,Quantity)>
<!ELEMENT customername (#PCDATA)>
<!ELEMENT age (#PCDATA)>
<!ELEMENT gender (#PCDATA)>
<!ELEMENT ItemId (#PCDATA)>
<!ELEMENT ItemName (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT Quantity (#PCDATA)>

=== iashtripathy/WebProgrammingPart1/xml/index.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE order SYSTEM "order.dtd">
<?xml-stylesheet type="text/xsl" href="order.xsl"?>
<order id="1">
    <customername>Rajat</customername>
    <age>30</age>
    <gender>M</gender>
    <Item>
        <ItemId>007</ItemId>
        <ItemName>Samsung</ItemName>
        <price>500</price>
        <Quantity>90</Quantity>
    </Item>
    <Item>
        <ItemId>501</ItemId>
        <ItemName>Apple</ItemName>
        <price>1001</price>
        <Quantity>33</Quantity>
    </Item>
</order>
